---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    app: "products"
    version: "1.0.1"
  name: "products-v101"
spec:
  ports:
  - port: 9090
    protocol: "TCP"
    targetPort: 9090
    name: "http"
  selector:
    app: "products"
    version: "1.0.1"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations: {}
  labels:
    version: "1.0.1"
    app: "products"
  name: "products-deployment-new"
spec:
  replicas: 1
  selector:
    matchLabels:
      version: "1.0.1"
      app: "products"
  template:
    metadata:
      annotations: {}
      labels:
        version: "1.0.1"
        app: "products"
    spec:
      containers:
      - image: "pubudu/products:1.0.1"
        imagePullPolicy: "Always"
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          tcpSocket:
            port: 9090
        name: "products-deployment-new"
        ports:
        - containerPort: 9090
          protocol: "TCP"
      nodeSelector: {}
