---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    app: "review"
  name: "review"
spec:
  ports:
  - port: 8080
    protocol: "TCP"
    targetPort: 8080
    name: "http"
  selector:
    app: "review"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations: {}
  labels:
    app: "review"
  name: "review-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "review"
  template:
    metadata:
      annotations: {}
      labels:
        app: "review"
    spec:
      containers:
      - image: "pubudu/review:1.0.0"
        imagePullPolicy: "Always"
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          tcpSocket:
            port: 8080
        name: "review-deployment"
        ports:
        - containerPort: 8080
          protocol: "TCP"
      nodeSelector: {}
